version: 1
type: view
name: products
model_name: strum_platform_model
sql_table_name: dbo.Products
identifiers:
- name: productid
  type: primary
  sql: concat(${productid},${data_period_raw})
- name: pgrpid
  type: foreign
  sql: concat(${prodgrp},${data_period_raw})
fields:
- name: productid
  field_type: dimension
  type: number
  hidden: true
  primary_key: true
  sql: ${TABLE}.productid

- name: bankprodid
  field_type: dimension
  type: string
  hidden: true
  primary_key: false
  description: ''
  sql: ${TABLE}.bankprodid
  searchable: false
  synonyms:
  - Product, Product Type, Account type

- name: instid
  field_type: dimension
  type: number
  hidden: true
  sql: ${TABLE}.instid

- name: product_type
  field_type: dimension
  type: string
  description: The type of the product (Retail or Commercial)
  sql: >-
    case when ${TABLE}.type = 1 then 'Retail' when ${TABLE}.type = 2 then
    'Commercial' else 'Unknown' end
  searchable: true

- name: product_description
  field_type: dimension
  type: string
  label: Product Description
  description: >-
    This is the name of the banking product used. Use this when asked about
    banking products.
  sql: ${TABLE}.proddesc
  searchable: true

- name: prodgrp
  field_type: dimension
  type: number
  hidden: true
  description: >-
    Product Group ID, which corresponds to the Product Group and Service Group
    tables
  sql: ${TABLE}.prodgrp

- name: ruleset
  field_type: dimension
  type: number
  hidden: true
  sql: ${TABLE}.ruleset

- name: sls_pnt_val
  field_type: dimension
  type: number
  hidden: true
  sql: ${TABLE}.sls_pnt_val

- name: sls_cur_val
  field_type: dimension
  type: number
  hidden: true
  sql: ${TABLE}.sls_cur_val

- name: source
  field_type: dimension
  type: string
  hidden: true
  primary_key: false
  description: The source of the product (e.g. CC = Credit Card)
  sql: ${TABLE}.source
  searchable: true

- name: term
  field_type: dimension
  type: number
  hidden: true
  primary_key: false
  description: ''
  sql: ${TABLE}.term
  searchable: false

- name: data_period
  field_type: dimension_group
  type: time
  datatype: date
  description: >-
    This is the period of the snapshot, and it is always the date of the end
    of the month
  timeframes:
  - raw
  - date
  - month
  sql: ${TABLE}.DataPeriod 