version: 1
type: view
name: product_group
model_name: strum_platform_model
sql_table_name: dbo.ProdGrp
identifiers:
- name: sgrpid
  type: foreign
  sql: concat(${sgrpid},${data_period_raw})
- name: pgrpid
  type: primary
  sql: concat(${pgrpid},${data_period_raw})
fields:
- name: pgrpid
  field_type: dimension
  type: number
  hidden: true
  primary_key: true
  description: Product Group ID
  sql: ${TABLE}.pgrpid

- name: sgrpid
  field_type: dimension
  type: number
  hidden: true
  description: Service Group ID
  sql: ${TABLE}.sgrpid

- name: pgrpldesc
  field_type: dimension
  type: string
  label: Product Group Description
  description: Product Group Description
  sql: ${TABLE}.pgrpldesc
  searchable: true

- name: pgrpsdesc
  field_type: dimension
  type: string
  label: Product Group Short Description
  description: Product Group Short Description
  sql: ${TABLE}.pgrpsdesc
  searchable: true

- name: busunit
  field_type: dimension
  type: string
  hidden: true
  sql: ${TABLE}.busunit
  searchable: true

- name: status
  field_type: dimension
  type: number
  hidden: true
  sql: ${TABLE}.status

- name: data_period
  field_type: dimension_group
  type: time
  datatype: date
  description: >-
    This is the period of the snapshot, and it is always the date of the end
    of the month
  timeframes:
  - raw
  - date
  - month
  sql: ${TABLE}.DataPeriod  